# Generated by Django 5.2.1 on 2025-12-10 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_setup', '0003_alter_ciclo_unique_together_alter_carrera_unidad_and_more'),
        ('users', '0002_alter_docentes_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquesHorariosDefinicion',
            fields=[
                ('bloque_def_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_bloque', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
            ],
            options={
                'verbose_name': 'Bloque Horario (Definición)',
                'verbose_name_plural': 'Bloques Horarios (Definiciones)',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('nombre_bloque', 'hora_inicio', 'hora_fin', 'turno', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionRestricciones',
            fields=[
                ('restriccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_restriccion', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('tipo_aplicacion', models.CharField(choices=[('GLOBAL', 'Global'), ('DOCENTE', 'Docente'), ('MATERIA', 'Materia'), ('AULA', 'Aula/Espacio'), ('CARRERA', 'Carrera'), ('PERIODO', 'Período')], max_length=50)),
                ('entidad_id_1', models.IntegerField(blank=True, help_text='ID del docente, materia, aula, etc.', null=True)),
                ('entidad_id_2', models.IntegerField(blank=True, help_text='ID secundario para relaciones', null=True)),
                ('valor_parametro', models.CharField(blank=True, help_text='Valor de la restricción', max_length=255, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('periodo_aplicable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_configuradas', to='academic_setup.periodoacademico')),
            ],
            options={
                'verbose_name': 'Configuración de Restricción',
                'verbose_name_plural': 'Configuraciones de Restricciones',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('grupo_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=50)),
                ('numero_estudiantes_estimado', models.IntegerField(blank=True, null=True)),
                ('turno_preferente', models.CharField(blank=True, choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1, null=True)),
                ('ciclo_semestral', models.IntegerField(blank=True, help_text='Ciclo académico al que pertenece este grupo/materia (ej. 1, 2, ..., 10)', null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academic_setup.carrera')),
                ('docente_asignado_directamente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_asignados_directo', to='users.docentes')),
                ('materias', models.ManyToManyField(related_name='grupos', to='academic_setup.materias')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academic_setup.periodoacademico')),
            ],
            options={
                'verbose_name': 'Grupo/Sección',
                'verbose_name_plural': 'Grupos/Secciones',
                'ordering': ['-grupo_id'],
                'unique_together': {('codigo_grupo', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleAuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadDocentes',
            fields=[
                ('disponibilidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('esta_disponible', models.BooleanField(default=True)),
                ('preferencia', models.SmallIntegerField(default=0, help_text='Ej: 0=Neutral, 1=Preferido, -1=No preferido')),
                ('origen_carga', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel')], default='MANUAL', max_length=10)),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_en_bloque', to='scheduling.bloqueshorariosdefinicion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='users.docentes')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_docentes', to='academic_setup.periodoacademico')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Docente',
                'verbose_name_plural': 'Disponibilidades de Docentes',
                'unique_together': {('docente', 'periodo', 'dia_semana', 'bloque_horario')},
            },
        ),
        migrations.CreateModel(
            name='HorariosAsignados',
            fields=[
                ('horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloque_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_en_bloque', to='scheduling.bloqueshorariosdefinicion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='users.docentes')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_en_espacio', to='academic_setup.espaciosfisicos')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_programadas', to='scheduling.grupos')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases_impartidas', to='academic_setup.materias')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_del_periodo', to='academic_setup.periodoacademico')),
            ],
            options={
                'verbose_name': 'Horario Asignado',
                'verbose_name_plural': 'Horarios Asignados',
                'unique_together': {('docente', 'periodo', 'dia_semana', 'bloque_horario'), ('espacio', 'periodo', 'dia_semana', 'bloque_horario'), ('grupo', 'materia', 'periodo', 'dia_semana', 'bloque_horario'), ('grupo', 'periodo', 'dia_semana', 'bloque_horario')},
            },
        ),
    ]
