# Generated by Django 5.2.1 on 2025-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosasignados',
            name='updated_at',
        ),
    ]
