# Generated by Django 5.2.1 on 2025-12-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_horariosasignados_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosasignados',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
